Revert "explicitly take const references in the LuaSignalTrampoline"
This reverts commit fba4d288e51ed7b422528b9587302c3bdf1a2383.

Causes error C2529 (reference to reference is illegal) on VC2008 (at least).